Adapt volatile process C# scripts to avoid error CS8983
Update volatile process program code to avoid CS8983 (A 'struct' with field initializers must include an explicitly declared constructor)

After the changes in C# discussed at https://github.com/dotnet/csharplang/issues/5552
For the upstream changes, see https://github.com/dotnet/roslyn/pull/58581

For discussion of the change, also see https://github.com/dotnet/sdk/issues/23971