Adapt to .NET 7-based botlab client and volatile process
Avoid compilation errors seen when combining the previous volatile process program code with the new .NET 7-based client (with a new version of CSharp scripting): Remove obsolete code from the volatile process program that causes a compilation error in the new client. The overall program did not use this C# method anymore anyway.

For the upstream update to .NET 7 build and new C# scripting, see https://github.com/elm-fullstack/elm-fullstack/commit/c3715823e07cda567ba720f3e0398e75b7061a06

Following is the error observed when attempting to use the previous volatile process programs with the new client:
----
Microsoft.CodeAnalysis.Scripting.CompilationErrorException: (47,29): error CS1069: The type name 'SHA256Managed' could not be found in the namespace 'System.Security.Cryptography'. This type has been forwarded to assembly 'System.Security.Cryptography, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' Consider adding a reference to that assembly.
----